<Project>
  <PropertyGroup>
    <Version>1.0.3</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <ProductDisplayName>Colony Optimiser</ProductDisplayName>
    <ProductPublisher>Colony Optimiser contributors</ProductPublisher>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
